#!/usr/bin/env python3
"""
make_setup.py  —  Run ONCE on your Mac to generate the portable installer.

  python3 make_setup.py

Produces:  WB_Election_Intel_Setup.py
  → Single Python file, works on macOS AND Windows
  → Double-click on Windows  /  python3 WB_Election_Intel_Setup.py on Mac
  → Installs everything (ffmpeg, venv, pip packages, Playwright) and extracts
    all project files into a WB_Election_Intel/ folder.
"""

import zlib, base64, sys, os
from pathlib import Path

HERE = Path(__file__).parent

# ── Files to embed ─────────────────────────────────────────────────────────────
FILES = {
    "proxy_local.py":                      HERE / "proxy_local.py",
    "wb_live_intel_dashboard.html":        HERE / "wb_live_intel_dashboard.html",
    "wb_election_intel_presentation.html": HERE / "wb_election_intel_presentation.html",
    "build_assets.py":                     HERE / "build_assets.py",
    "README.md":                           HERE / "README.md",
    "LOCAL_LLM_GUIDE.md":                 HERE / "LOCAL_LLM_GUIDE.md",
}

# ── Encode each file ────────────────────────────────────────────────────────────
def encode(path: Path) -> str:
    raw = path.read_bytes()
    return base64.b64encode(zlib.compress(raw, 9)).decode("ascii")

print("Reading and compressing project files...")
embedded = {}
total_raw = total_enc = 0
for name, path in FILES.items():
    if not path.exists():
        print(f"  ⚠  MISSING  {name}  — skipping")
        continue
    raw_size = path.stat().st_size
    enc      = encode(path)
    embedded[name] = enc
    total_raw += raw_size
    total_enc += len(enc)
    print(f"  ✓  {name:<45}  {raw_size//1024:>4}KB → {len(enc)//1024:>4}KB (b64z)")

print(f"\nTotal: {total_raw//1024}KB raw → {total_enc//1024}KB embedded")

# ── Build the embedded-dict literal ────────────────────────────────────────────
lines = ["EMBEDDED = {\n"]
for name, enc in embedded.items():
    # split into 96-char lines for readability / editor safety
    chunks = [enc[i:i+96] for i in range(0, len(enc), 96)]
    lines.append(f'    "{name}": (\n')
    for chunk in chunks:
        lines.append(f'        "{chunk}"\n')
    lines.append("    ),\n")
lines.append("}\n")
EMBEDDED_BLOCK = "".join(lines)

# ── The setup script template ───────────────────────────────────────────────────
TEMPLATE = r'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
WB Election Intel — One-click installer
Works on macOS AND Windows  (Python 3.8+ required)

macOS / Linux:
    python3 WB_Election_Intel_Setup.py

Windows (two options):
    Double-click this file in Explorer
    — OR —
    python WB_Election_Intel_Setup.py
"""

import sys, os, platform, subprocess, shutil, zlib, base64, textwrap
from pathlib import Path

# ══════════════════════════════════════════════════════════════════════
#  EMBEDDED PROJECT FILES  (auto-generated by make_setup.py)
# ══════════════════════════════════════════════════════════════════════
%%EMBEDDED_BLOCK%%
# ══════════════════════════════════════════════════════════════════════

IS_WIN  = sys.platform == "win32"
IS_MAC  = sys.platform == "darwin"
IS_LIN  = sys.platform.startswith("linux")

CYAN    = "\033[96m" if not IS_WIN else ""
GREEN   = "\033[92m" if not IS_WIN else ""
YELLOW  = "\033[93m" if not IS_WIN else ""
RED     = "\033[91m" if not IS_WIN else ""
BOLD    = "\033[1m"  if not IS_WIN else ""
RESET   = "\033[0m"  if not IS_WIN else ""

def banner(msg):
    print(f"\n{BOLD}{CYAN}{'═'*60}{RESET}")
    print(f"{BOLD}{CYAN}  {msg}{RESET}")
    print(f"{BOLD}{CYAN}{'═'*60}{RESET}\n")

def step(msg):   print(f"  {GREEN}▶{RESET}  {msg}")
def warn(msg):   print(f"  {YELLOW}⚠{RESET}  {msg}")
def ok(msg):     print(f"  {GREEN}✓{RESET}  {msg}")
def err(msg):    print(f"  {RED}✕{RESET}  {msg}")

def run(cmd, **kw):
    return subprocess.run(cmd, check=True, **kw)

def run_quietly(cmd, **kw):
    return subprocess.run(cmd, check=True,
                          stdout=subprocess.DEVNULL,
                          stderr=subprocess.DEVNULL, **kw)

# ── Python version check ────────────────────────────────────────────
if sys.version_info < (3, 8):
    print(f"{RED}Python 3.8 or newer is required. You have {sys.version}{RESET}")
    sys.exit(1)

banner("WB Election Intel — Setup")
print(f"  Platform : {platform.system()} {platform.release()}")
print(f"  Python   : {sys.version.split()[0]}")

# ── Choose install folder ───────────────────────────────────────────
DEFAULT = Path.home() / "WB_Election_Intel"
print(f"\n  Default install folder: {DEFAULT}")
ans = input("  Press Enter to accept, or type a different path: ").strip()
DEST = Path(ans) if ans else DEFAULT
DEST.mkdir(parents=True, exist_ok=True)
ok(f"Install folder: {DEST}")

# ── Extract embedded files ──────────────────────────────────────────
banner("Extracting project files")
for name, b64z in EMBEDDED.items():
    out = DEST / name
    out.write_bytes(zlib.decompress(base64.b64decode(b64z.replace("\n",""))))
    ok(f"  {name}  ({out.stat().st_size//1024}KB)")

# ── Virtual environment ─────────────────────────────────────────────
banner("Setting up Python virtual environment")
VENV = DEST / "venv"
if VENV.exists():
    warn("venv already exists — skipping creation")
else:
    step("Creating venv...")
    run([sys.executable, "-m", "venv", str(VENV)])
    ok("venv created")

PY  = VENV / ("Scripts/python.exe" if IS_WIN else "bin/python3")
PIP = VENV / ("Scripts/pip.exe"    if IS_WIN else "bin/pip3")

# ── pip packages ────────────────────────────────────────────────────
banner("Installing Python packages")
PACKAGES = ["playwright", "python-pptx", "Pillow", "yt-dlp", "pypdf"]
step(f"Installing: {', '.join(PACKAGES)}")
run([str(PIP), "install", "--upgrade", "pip"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
run([str(PIP), "install"] + PACKAGES)
ok("pip packages installed")

step("Installing Playwright Chromium browser...")
run([str(PY), "-m", "playwright", "install", "chromium"])
ok("Playwright Chromium installed")

# ── ffmpeg ──────────────────────────────────────────────────────────
banner("Installing ffmpeg")

def ffmpeg_ok():
    return shutil.which("ffmpeg") is not None or (DEST / "ffmpeg.exe").exists() or (DEST / "ffmpeg").exists()

if ffmpeg_ok():
    ok("ffmpeg already available")
elif IS_MAC:
    if shutil.which("brew"):
        step("Installing via Homebrew...")
        try:
            run(["brew", "install", "ffmpeg"])
            ok("ffmpeg installed via Homebrew")
        except subprocess.CalledProcessError:
            warn("Homebrew install failed — downloading static binary...")
            _install_ffmpeg_mac(DEST)
    else:
        warn("Homebrew not found — downloading static ffmpeg binary...")
        _install_ffmpeg_mac(DEST)
elif IS_WIN:
    _install_ffmpeg_win(DEST)
else:
    warn("Linux detected — trying apt/dnf...")
    try:
        run_quietly(["sudo", "apt-get", "install", "-y", "ffmpeg"])
        ok("ffmpeg installed via apt")
    except Exception:
        try:
            run_quietly(["sudo", "dnf", "install", "-y", "ffmpeg"])
            ok("ffmpeg installed via dnf")
        except Exception:
            warn("Could not auto-install ffmpeg. Please install manually: https://ffmpeg.org")

def _install_ffmpeg_mac(dest):
    import urllib.request, tarfile, tempfile
    URL = "https://evermeet.cx/ffmpeg/getrelease/ffmpeg/zip"
    step("Downloading ffmpeg static binary for macOS...")
    try:
        import zipfile, io
        with urllib.request.urlopen(URL, timeout=120) as r:
            data = r.read()
        with zipfile.ZipFile(io.BytesIO(data)) as zf:
            for member in zf.namelist():
                if "ffmpeg" in member.lower() and not member.endswith("/"):
                    target = dest / "ffmpeg"
                    target.write_bytes(zf.read(member))
                    target.chmod(0o755)
                    ok(f"ffmpeg extracted to {target}")
                    return
    except Exception as e:
        warn(f"Download failed: {e}")
        warn("Please install ffmpeg manually: brew install ffmpeg")

def _install_ffmpeg_win(dest):
    import urllib.request, zipfile, io
    URL = ("https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/"
           "ffmpeg-master-latest-win64-gpl.zip")
    step("Downloading ffmpeg static binary for Windows (~80 MB)...")
    try:
        with urllib.request.urlopen(URL, timeout=300) as r:
            data = r.read()
        ok("Downloaded. Extracting ffmpeg.exe...")
        with zipfile.ZipFile(io.BytesIO(data)) as zf:
            for member in zf.namelist():
                if member.endswith("bin/ffmpeg.exe"):
                    target = dest / "ffmpeg.exe"
                    target.write_bytes(zf.read(member))
                    ok(f"ffmpeg.exe extracted to {target}")
                    return
    except Exception as e:
        warn(f"Download failed: {e}")
        warn("Please download ffmpeg manually from https://ffmpeg.org/download.html")
        warn("Extract ffmpeg.exe into: " + str(dest))

# ── Launchers ───────────────────────────────────────────────────────
banner("Creating launchers")

if IS_WIN:
    bat = DEST / "START.bat"
    bat.write_text(textwrap.dedent(f"""\
        @echo off
        title WB Election Intel
        cd /d "%~dp0"
        set PATH=%~dp0;%PATH%
        echo Starting WB Election Intel proxy...
        venv\\Scripts\\python.exe proxy_local.py --backend ollama
        pause
    """))
    bat2 = DEST / "START_groq.bat"
    bat2.write_text(textwrap.dedent(f"""\
        @echo off
        title WB Election Intel — Groq
        cd /d "%~dp0"
        set PATH=%~dp0;%PATH%
        set /p GROQ_API_KEY=Enter Groq API key:
        venv\\Scripts\\python.exe proxy_local.py --backend groq
        pause
    """))
    ok("START.bat  (Ollama backend)")
    ok("START_groq.bat  (Groq cloud backend)")
else:
    sh = DEST / "start.sh"
    sh.write_text(textwrap.dedent(f"""\
        #!/bin/bash
        cd "$(dirname "$0")"
        export PATH="$(dirname "$0"):$PATH"
        source venv/bin/activate
        echo "Starting WB Election Intel proxy (Ollama)..."
        python3 proxy_local.py --backend ollama
    """))
    sh.chmod(0o755)
    sh_groq = DEST / "start_groq.sh"
    sh_groq.write_text(textwrap.dedent(f"""\
        #!/bin/bash
        cd "$(dirname "$0")"
        export PATH="$(dirname "$0"):$PATH"
        source venv/bin/activate
        read -p "Enter Groq API key: " GROQ_API_KEY
        export GROQ_API_KEY
        python3 proxy_local.py --backend groq
    """))
    sh_groq.chmod(0o755)
    cmd = DEST / "START.command"   # macOS double-click launcher
    cmd.write_text(textwrap.dedent(f"""\
        #!/bin/bash
        cd "$(dirname "$0")"
        export PATH="$(dirname "$0"):$PATH"
        source venv/bin/activate
        python3 proxy_local.py --backend ollama
    """))
    cmd.chmod(0o755)
    ok("start.sh  +  start_groq.sh  +  START.command (macOS double-click)")

# ── Ollama reminder ─────────────────────────────────────────────────
banner("Ollama — Local AI (recommended)")
if shutil.which("ollama"):
    ok("Ollama is already installed")
    step("Pulling llama3.1:8b model (may take a few minutes)...")
    try:
        run(["ollama", "pull", "llama3.1:8b"])
        ok("llama3.1:8b ready")
    except Exception:
        warn("Could not pull model — run: ollama pull llama3.1:8b")
else:
    warn("Ollama not installed. To use the FREE local AI backend:")
    if IS_WIN:
        print("    1. Download: https://ollama.com/download/windows")
        print("    2. Run the installer, then restart this terminal")
        print("    3. Run:  ollama pull llama3.1:8b")
    elif IS_MAC:
        print("    1. Download: https://ollama.com/download/mac")
        print("       OR run:   curl -fsSL https://ollama.com/install.sh | sh")
        print("    2. Run:  ollama pull llama3.1:8b")
    print()
    print("    Alternatively use Groq (free, fast, cloud):")
    print("    → Get key: https://console.groq.com")
    print("    → Start:   python3 proxy_local.py --backend groq")

# ── Done ────────────────────────────────────────────────────────────
banner("Setup complete!")
print(f"  {GREEN}Install folder:{RESET} {DEST}")
print()
print("  ┌─── HOW TO RUN ───────────────────────────────────────────┐")
if IS_WIN:
    print(f"  │  1. Double-click  START.bat  in {DEST.name}/")
    print(f"  │  2. Open  wb_live_intel_dashboard.html  in Chrome")
else:
    print(f"  │  1. Double-click  START.command   (macOS Finder)")
    print(f"  │     OR run:  cd {DEST} && ./start.sh")
    print(f"  │  2. Open  wb_live_intel_dashboard.html  in Chrome")
print("  │  3. Click [Fetch Now] for first cycle                   │")
print("  │  4. Cycles auto-refresh every 30 min                    │")
print("  └──────────────────────────────────────────────────────────┘")
print()
print("  API backend options:")
print("    --backend ollama   (default, free, local)")
print("    --backend groq     (fast, free tier at console.groq.com)")
print("    --backend gemini   (Google AI)")
print()

if IS_WIN:
    input("Press Enter to close...")
'''

# ── Inject the embedded block ───────────────────────────────────────────────────
OUTPUT_SCRIPT = TEMPLATE.replace("%%EMBEDDED_BLOCK%%", EMBEDDED_BLOCK)

# ── Write the output file ───────────────────────────────────────────────────────
OUT = HERE / "WB_Election_Intel_Setup.py"
OUT.write_text(OUTPUT_SCRIPT, encoding="utf-8")

size_kb = OUT.stat().st_size // 1024
print(f"\n{'='*60}")
print(f"✅  Generated: {OUT.name}  ({size_kb} KB)")
print(f"{'='*60}")
print()
print("  Share this single file. On the target machine:")
print()
print("  macOS / Linux:")
print("    python3 WB_Election_Intel_Setup.py")
print()
print("  Windows:")
print("    Double-click the file in Explorer")
print("    (Python must be installed from python.org or Microsoft Store)")
print()
